### ISSUE TITLE
SetPDFSelectionAs verursacht Fehler

### ISSUE THREAD

**Issue by HansSiem** [lutz/citavi-addons#21]
Das Add-On
https://github.com/lutz/citavi-addons/tree/master/src/SetPDFSelectionAsAddon
verursacht diesen Bug:
https://github.com/Citavi/Citavi/issues/2219

**Comment by lutz** [comment]
@HansSiem Bitte mit den aktuellen DLLs prüfen Jana hatte mich auf den Fehler aufmerksam gemacht, dass sollte nun auch wieder funktionieren.
